/**
 * Pins the converted Camp Hope forms (src/lib/camp-hope-forms.ts, generated by
 * scripts/convert-elexio-forms.ts) to what Elexio actually asked, and checks
 * that the family forms really create households and price correctly.
 */
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";

import { CAMP_HOPE_FORMS } from "./camp-hope-forms.ts";
import { perCamperTiers, type ConvertedForm } from "./elexio-convert.ts";
import { buildFamilyIntake, formSupportsFamilyIntake } from "./form-family-intake.ts";
import { FIELD_TYPES, expandRepeats, validateSubmission, type FormAnswers, type FormAudience, type FormField } from "./forms.ts";
import { householdTuitionCents } from "./pricing.ts";

function byAudience(audience: FormAudience): ConvertedForm {
  const form = CAMP_HOPE_FORMS.find((f) => f.audience === audience);
  assert.ok(form, `missing ${audience}`);
  return form;
}

function asFields(form: ConvertedForm): FormField[] {
  return form.fields.map((f, i) => ({ ...f, id: `f${i}`, camp_id: "camp", form_id: "form", display_order: i }));
}

function find(form: ConvertedForm, key: string) {
  const f = form.fields.find((x) => x.field_key === key);
  assert.ok(f, `${form.audience} has no ${key}`);
  return f;
}

test("all five forms convert, in Elexio's order, with the row counts Elexio implies", () => {
  assert.deepEqual(
    CAMP_HOPE_FORMS.map((f) => [f.audience, f.fields.length, f.title]),
    [
      ["new_family", 35, "Camp Hope 2026 - New Families"],
      ["returning_family", 34, "Camp Hope 2026 - Returning Families"],
      ["new_adult", 62, "Camp Hope 2026 - New Adult Volunteers"],
      ["returning_adult", 34, "Camp Hope 2026 - Returning Adult Volunteers"],
      ["teen_volunteer", 68, "Camp Hope 2026 - Teen Volunteers"],
    ]
  );
  for (const form of CAMP_HOPE_FORMS) {
    const keys = form.fields.map((f) => f.field_key);
    assert.equal(new Set(keys).size, keys.length, `${form.audience} keys are unique`);
    for (const f of form.fields) {
      assert.ok((FIELD_TYPES as readonly string[]).includes(f.field_type), `${f.field_key}: ${f.field_type}`);
      assert.match(f.field_key, /^[a-z0-9_]{1,60}$/);
      if (f.visible_when) assert.ok(keys.indexOf(f.visible_when.field) < keys.indexOf(f.field_key), `${f.field_key} watches an earlier question`);
      if (f.repeat_count_field) assert.ok(keys.includes(f.repeat_count_field));
    }
  }
});

test("wording is Elexio's, typos and all", () => {
  const nf = byAudience("new_family");
  assert.equal(find(nf, "are_you_affiliated_with_a_church_or_community_if").label, "Are you affiliated with a Church or community? If so, which one(s)?");
  assert.equal(
    find(nf, "camper_grade").help_text,
    "Please fill in the grade that your child completes at the end of this current 2025-2026 school year. Please note, 2nd grade cabins are capped at 8 campers."
  );
  assert.equal(find(nf, "camper_count").help_text, "Please select the number of campers you will be registering");
  const adult = byAudience("new_adult");
  assert.equal(find(adult, "primary_emergecy_contact_phone").label, "Primary Emergecy Contact Phone");
  assert.match(nf.intro_text ?? "", /^NEW TO CAMP HOPE\? PLEASE READ THESE IMPORTANT NOTES BEFORE REGISTERING:/);
  assert.match(nf.intro_text ?? "", /please select the "Pay Later" option/);
  assert.match(nf.success_text ?? "", /Document Upload portal linked HERE \(https:\/\/form\.jotform\.com\/211527447357055\)/);
  const cancellation = nf.fields.find((f) => f.section === "Camp Hope Cancellation Policy" && f.field_type === "section_heading");
  assert.match(cancellation?.help_text ?? "", /• Camper cost includes a \$50 nonrefundable registration fee \(per family\)/);
  assert.match(cancellation?.help_text ?? "", /After July 1st there is no refund for cancellation/);
});

test("stored values differ from labels exactly where Elexio's keys did", () => {
  const nf = byAudience("new_family");
  assert.deepEqual(find(nf, "camper_grade").options[0], {
    value: "2nd",
    label: "2nd grade (Camper) - My child finishes 2nd grade at the end of this school year",
  });
  assert.deepEqual(
    find(nf, "photo_release_consent").options.map((o) => (typeof o === "string" ? o : o.value)),
    ["Yes, I consent", "No, I do not consent"]
  );
  assert.deepEqual(find(nf, "i_have_read_and_agree_to_camp_hope_s_cancellatio").options, [{ value: "Yes", label: "YES" }]);
  assert.deepEqual(find(nf, "camper_gender").options, ["Male", "Female"]);
  const teen = byAudience("teen_volunteer");
  assert.deepEqual(find(teen, "when_can_you_serve").options.at(-1), "Other");
  assert.deepEqual(find(teen, "when_can_you_serve").options[0], { value: "Whole Week", label: "I can serve the whole week - (Sunday to Saturday)" });
});

test("show-this-only-if rules carry over", () => {
  for (const audience of ["new_adult", "returning_adult", "teen_volunteer"] as const) {
    const form = byAudience(audience);
    assert.deepEqual(find(form, "please_enter_exactly_which_dates_you_are_availab").visible_when, {
      field: "when_can_you_serve",
      op: "eq",
      value: "Other",
    });
    assert.deepEqual(find(form, "are_you_a_practicing_christian").visible_when, { field: "are_you_a_practicing_catholic", op: "eq", value: "No" });
    assert.deepEqual(find(form, "if_not_a_practicing_christian_or_catholic_please").visible_when, {
      field: "are_you_a_practicing_christian",
      op: "eq",
      value: "No",
    });
  }
  for (const audience of ["new_adult", "teen_volunteer"] as const) {
    assert.deepEqual(find(byAudience(audience), "what_are_the_names_of_the_other_camps").visible_when, {
      field: "camp_experience",
      op: "eq",
      value: "I have attended other camps",
    });
  }
  const nf = byAudience("new_family");
  const check = nf.fields.find((f) => f.help_text === "Please double check that you filled your child’s age and grade correctly");
  assert.deepEqual(check?.visible_when, { field: "camper_count", op: "in", value: ["1", "2", "3", "4", "5"] });
});

test("the camper block repeats off Number of Campers and the discount-code notices are left out", () => {
  for (const audience of ["new_family", "returning_family"] as const) {
    const form = byAudience(audience);
    const repeated = form.fields.filter((f) => f.repeat_count_field === "camper_count").map((f) => f.field_key);
    assert.deepEqual(repeated, [
      "camper_first_name",
      "camper_last_name",
      "camper_gender",
      "camper_birth_date",
      "camper_age_at_camp",
      "camper_grade",
    ]);
    assert.deepEqual(find(form, "camper_count").options, ["1", "2", "3", "4", "5"]);
    assert.deepEqual(form.omitted.map((o) => o.text.split("\n").at(-1)), ["GENESIS", "TRINITY", "GOSPEL", "OMEGA"]);
    assert.ok(formSupportsFamilyIntake(asFields(form)));
  }
});

test("every volunteer form ends with a required drawn signature and creates no household", () => {
  for (const audience of ["new_adult", "returning_adult", "teen_volunteer"] as const) {
    const form = byAudience(audience);
    const last = form.fields.at(-1);
    assert.equal(last?.field_type, "signature");
    assert.equal(last?.label, "Digital Signature");
    assert.equal(last?.required, true);
    assert.equal(form.pricing, null);
    assert.equal(formSupportsFamilyIntake(asFields(form)), false);
  }
});

test("a three-camper family registration validates and yields three campers", () => {
  const form = byAudience("new_family");
  const fields = asFields(form);
  const answers: FormAnswers = {
    guardian_first_name: "Ann",
    guardian_last_name: "Lee",
    guardian_email: "Ann@Example.com",
    guardian_phone: "(908) 555-0100",
    address_street: "1040 Plainfield Ave",
    address_city: "Plainfield",
    address_state: "NJ",
    address_zip: "07060",
    are_you_affiliated_with_a_church_or_community_if: "People of Hope",
    camper_count: "3",
    how_did_you_hear_about_camp_hope: "Parish",
    primary_emergency_contact_first: "Cy",
    primary_emergency_contact_last: "Lee",
    emergency_contact_phone_number: "9085550101",
    secondary_emergency_contact_first: "Di",
    secondary_emergency_contact_last: "Lee",
    secondary_emergency_contact_phone_number: "9085550102",
    do_you_accept_the_medical_and_health_waiver: "Yes",
    photo_release_consent: "Yes, I consent",
    i_have_read_and_agree_to_camp_hope_s_cancellatio: "Yes",
  };
  const kids = [
    ["Bo", "Male", "2017-05-01", "8", "3rd"],
    ["Eve", "Female", "2015-02-11", "11", "5th"],
    ["Fay", "Female", "2012-09-30", "14", "9th"],
  ];
  kids.forEach(([first, gender, dob, age, grade], i) => {
    const n = i + 1;
    Object.assign(answers, {
      [`camper_first_name__${n}`]: first,
      [`camper_last_name__${n}`]: "Lee",
      [`camper_gender__${n}`]: gender,
      [`camper_birth_date__${n}`]: dob,
      [`camper_age_at_camp__${n}`]: age,
      [`camper_grade__${n}`]: grade,
    });
  });

  assert.deepEqual(validateSubmission(fields, answers), { ok: true });
  assert.equal(expandRepeats(fields, answers).filter((f) => f.section === "Camper 3").length, 6);

  const intake = buildFamilyIntake(fields, answers);
  assert.ok(intake.ok);
  assert.equal(intake.payload.guardian.email, "ann@example.com");
  assert.deepEqual(
    intake.payload.campers.map((c) => [c.first_name, c.gender, c.birth_date, c.grade]),
    [
      ["Bo", "male", "2017-05-01", 3],
      ["Eve", "female", "2015-02-11", 5],
      ["Fay", "female", "2012-09-30", 9],
    ]
  );

  // Missing camper 3's grade blocks; dropping to two campers does not.
  const missing = { ...answers, camper_grade__3: "" };
  assert.equal(validateSubmission(fields, missing).ok, false);
  assert.deepEqual(validateSubmission(fields, { ...missing, camper_count: "2" }), { ok: true });
});

test("tuition: $595 per camper before April 16, $625 after, priced per household", () => {
  const pricing = byAudience("new_family").pricing;
  assert.deepEqual(pricing, {
    amount_cents: 62500,
    early_amount_cents: 59500,
    early_ends_on: "2026-04-16",
    max_campers: 5,
    accepts_pay_later: true,
  });
  assert.deepEqual(byAudience("returning_family").pricing, pricing);

  const tiers = perCamperTiers(pricing!);
  const early = "2027-04-16";
  assert.equal(householdTuitionCents(tiers, 1, "2027-04-15", early), 59500);
  assert.equal(householdTuitionCents(tiers, 1, "2027-04-16", early), 62500);
  assert.equal(householdTuitionCents(tiers, 3, "2027-05-01", early), 187500);
  assert.equal(householdTuitionCents(tiers, 5, "2027-01-10", early), 297500);
  // Beyond the published tiers the largest one applies, as in family_tuition_cents.
  assert.equal(householdTuitionCents(tiers, 6, "2027-05-01", early), 312500);
  assert.equal(householdTuitionCents([], 2, "2027-05-01", early), null);

  // The seed SQL was generated from these same tiers.
  const sql = readFileSync(new URL("../../supabase/seed/camp-hope-pricing.sql", import.meta.url), "utf8");
  for (const t of tiers) {
    assert.ok(sql.includes(`(v_camp_id, v_season_id, ${t.camper_count}, ${t.early_cents}, ${t.regular_cents})`), `tier ${t.camper_count} in SQL`);
  }
  assert.match(sql, /make_date\(v_year, 4, 16\)/);
});

test("the forms seed carries every converted question, unpublished", () => {
  const sql = readFileSync(new URL("../../supabase/seed/camp-hope-forms.sql", import.meta.url), "utf8");
  const json = /\$elexio\$(.*)\$elexio\$/s.exec(sql)?.[1];
  assert.ok(json);
  const seeded = JSON.parse(json) as { audience: string; fields: { field_key: string }[] }[];
  assert.deepEqual(
    seeded.map((f) => [f.audience, f.fields.map((x) => x.field_key)]),
    CAMP_HOPE_FORMS.map((f) => [f.audience, f.fields.map((x) => x.field_key)])
  );
  assert.match(sql, /published_at\)\s+values\s+\([^)]*, null\)/);
  assert.match(sql, /if exists \(select 1 from public\.form_definitions where period_id = v_period_id\)/);
});
