-- Generated by scripts/convert-elexio-forms.ts from the Elexio form JSON. Do not edit by hand; re-run the script.
--
-- Camp Hope tuition for the active season, from the Elexio camper block:
--   $625 per camper, $595 per camper before 04-16 (Elexio's 2026 date,
--   carried to the active season's year). Up to 5 campers per registration.
--
-- pricing_tiers holds the TOTAL for a household of N campers, and
-- family_tuition_cents() charges the largest tier <= the family's camper count.
--
-- Tier 1 is exact and is upserted. Tiers 2-5 are N x the per-camper price:
-- Elexio gave families a discount through codes (2 GENESIS, 3 TRINITY,
-- 4 GOSPEL, 5 OMEGA), but the discount AMOUNTS live in Elexio's admin and are
-- not in the form data. They are inserted only when missing, so once a
-- director enters the real discounted totals, re-running this leaves them be.
-- A 5-camper tier is included because the forms allow 5 campers; without
-- it a 5-camper family would be charged the 4-camper total.
--
-- Pay Later stays available: registration creates the invoice and schedule
-- without taking a card, and a check is recorded from Finance as an offline
-- payment.

do $do$
declare
  v_camp_slug constant text := 'camphope';
  v_camp_id   uuid;
  v_season_id uuid;
  v_year      int;
begin
  select id into v_camp_id from public.camps where slug = v_camp_slug;
  if v_camp_id is null then
    raise exception 'No camp with slug %', v_camp_slug;
  end if;

  select id, year into v_season_id, v_year
    from public.seasons
   where camp_id = v_camp_id and is_active
   order by year desc
   limit 1;
  if v_season_id is null then
    raise exception 'Camp % has no active season', v_camp_slug;
  end if;

  -- The early rate applies before this date (family_tuition_cents: as_of < date).
  update public.seasons
     set early_rate_ends_on = make_date(v_year, 4, 16)
   where id = v_season_id;

  insert into public.pricing_tiers (camp_id, season_id, camper_count, early_cents, regular_cents)
  values
    (v_camp_id, v_season_id, 1, 59500, 62500)
  on conflict (season_id, camper_count) do update
    set early_cents = excluded.early_cents,
        regular_cents = excluded.regular_cents;

  insert into public.pricing_tiers (camp_id, season_id, camper_count, early_cents, regular_cents)
  values
    (v_camp_id, v_season_id, 2, 119000, 125000),
    (v_camp_id, v_season_id, 3, 178500, 187500),
    (v_camp_id, v_season_id, 4, 238000, 250000),
    (v_camp_id, v_season_id, 5, 297500, 312500)
  on conflict (season_id, camper_count) do nothing;
end;
$do$;
