/**
 * Rebuilds Camp Hope's five Elexio registration forms in Camper Roster's form
 * model (GitHub issue #16). Reads the Ministry Forms JSON for each form and
 * writes three files, so the mapping is reproducible rather than retyped:
 *
 *   src/lib/camp-hope-forms.ts          the converted forms, for tests and review
 *   supabase/seed/camp-hope-forms.sql   unpublished v1 drafts for each 2027 period
 *   supabase/seed/camp-hope-pricing.sql per-camper tuition tiers from the forms
 *
 * The JSON lives in the CMO repo. Export it, then run:
 *
 *   mkdir -p /tmp/elexio && for f in new-families returning-families \
 *     new-adult-volunteers returning-adult-volunteers teen-volunteers; do
 *     git -C ../cmo_agent show origin/main:clients/camp-hope/knowledge/elexio-forms/$f.json > /tmp/elexio/$f.json
 *   done
 *   node --experimental-strip-types scripts/convert-elexio-forms.ts /tmp/elexio
 */
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

import {
  convertElexioForm,
  perCamperTiers,
  type ConvertedForm,
  type ElexioForm,
  type KeyOverride,
} from "../src/lib/elexio-convert.ts";
import type { FormAudience } from "../src/lib/forms.ts";

const SOURCES: { file: string; audience: FormAudience; elexioId: string }[] = [
  { file: "new-families.json", audience: "new_family", elexioId: "c4a0567d-7795-4639-b60b-cf8ef6a6c562" },
  { file: "returning-families.json", audience: "returning_family", elexioId: "f42c4476-9b64-4b5c-98a1-52aceeddaa35" },
  { file: "new-adult-volunteers.json", audience: "new_adult", elexioId: "6af8cf45-c248-4395-83b8-d1b1500c06b7" },
  { file: "returning-adult-volunteers.json", audience: "returning_adult", elexioId: "e9088a37-6436-4682-b5b0-9f18cd5bd7de" },
  { file: "teen-volunteers.json", audience: "teen_volunteer", elexioId: "18b7c1bb-eda2-46cb-941b-0ae3216e186d" },
];

/**
 * Questions whose answers create the household (see FAMILY_INTAKE_KEYS in
 * src/lib/form-family-intake.ts). Keyed by Elexio field id; the two family
 * forms share ids, as do the three volunteer forms.
 */
const KEY_OVERRIDES: Record<string, KeyOverride> = {
  "9805f7a1-8fe3-40c0-a89a-04805c56e2f6": { first: "guardian_first_name", last: "guardian_last_name" },
  "1e4fb5dc-4376-4ffa-81f4-25ec5e50604b": "guardian_email",
  "5fd5b982-c471-404e-abd8-a83f88c60f14": "guardian_phone",
  "5652d9eb-12ea-41c5-9242-ad29274c06cb": {
    street: "address_street",
    city: "address_city",
    state: "address_state",
    zip: "address_zip",
  },
  "dcf010ec-aaf1-4d4f-aa2f-af72822251f3": "camper_count",
  "10ce7067-e794-48ac-9578-d67483c02ad8": { first: "camper_first_name", last: "camper_last_name" },
  "85f6000b-1831-4b68-89d9-a5e53239863a": "camper_gender",
  "aac58ce6-e282-49b7-8cd8-d50b703df392": "camper_birth_date",
  "87d2e46d-5a48-4372-91c5-3788947e1aa6": "camper_age_at_camp",
  "1778769f-2a86-413c-b9ef-2b7e7e176083": "camper_grade",
  "fa1584d4-916c-4d11-ab89-b868ee51e231": { first: "primary_emergency_contact_first", last: "primary_emergency_contact_last" },
  "70b90ad3-a5b2-4cb8-a89f-f94df4e3d168": { first: "volunteer_first_name", last: "volunteer_last_name" },
  "2cdbe923-ef6a-4214-ac09-9941c7c40a1a": "volunteer_email",
  "9adb7ae2-87e7-4c1e-a8cc-e9a933ec9867": "volunteer_phone",
  "c1862522-9537-4ec9-9cd3-60912e1ba237": "date_of_birth",
};

/**
 * The four "enter the code" notices told families which Elexio discount code
 * to type at checkout. Camper Roster prices the household from its camper
 * count, so there is no code to enter and the notice would only confuse.
 */
const FAMILY_CODE_REASON =
  "Family discount code notice. Camper Roster applies family pricing from the number of campers (pricing_tiers), so there is no code to enter.";
const OMIT: Record<string, string> = {
  "836db208-5e5c-4d4a-9790-070eef782997": FAMILY_CODE_REASON,
  "885a990d-9562-4f0f-9a71-284f10a2a8bb": FAMILY_CODE_REASON,
  "e4ebe603-db56-4679-b797-33f23d4b83c6": FAMILY_CODE_REASON,
  "90bd9825-f102-4069-99a4-ca5a8196ad33": FAMILY_CODE_REASON,
};

const sourceDir = process.argv[2];
if (!sourceDir) {
  console.error("Usage: node --experimental-strip-types scripts/convert-elexio-forms.ts <dir with the five Elexio JSON files>");
  process.exit(1);
}

const forms: ConvertedForm[] = SOURCES.map(({ file, audience, elexioId }) => {
  const raw = JSON.parse(readFileSync(join(sourceDir, file), "utf8")) as { success?: boolean; data?: ElexioForm };
  if (!raw.data || raw.data.id !== elexioId) {
    throw new Error(`${file} is not Elexio form ${elexioId}.`);
  }
  return convertElexioForm(raw.data, { audience, keyOverrides: KEY_OVERRIDES, omit: OMIT });
});

const root = join(import.meta.dirname, "..");
const HEADER = "Generated by scripts/convert-elexio-forms.ts from the Elexio form JSON. Do not edit by hand; re-run the script.";

// 1. Data module -------------------------------------------------------------------
writeFileSync(
  join(root, "src/lib/camp-hope-forms.ts"),
  `// ${HEADER}\nimport type { ConvertedForm } from "./elexio-convert.ts";\n\n` +
    `export const CAMP_HOPE_FORMS: ConvertedForm[] = ${JSON.stringify(forms, null, 2)};\n`
);

// 2. Form drafts ---------------------------------------------------------------------
const formsJson = JSON.stringify(
  forms.map((f) => ({
    audience: f.audience,
    title: f.title,
    intro_text: f.intro_text,
    success_text: f.success_text,
    fields: f.fields.map(({ elexio_id: _id, ...field }) => field),
  }))
);
if (formsJson.includes("$elexio$")) throw new Error("Form text collides with the SQL dollar quote.");

writeFileSync(
  join(root, "supabase/seed/camp-hope-forms.sql"),
  `-- ${HEADER}
--
-- Camp Hope's five Elexio registration forms (GitHub issue #16) as version 1
-- of each 2027 registration period's form, UNPUBLISHED: published_at stays null
-- until a director reviews the draft in Admin > Forms and publishes it.
--
-- Requires migration 20261008120000_form_repeats_and_family_intake.sql
-- (radio type, repeat_count_field, success_text).
--
-- Idempotent: a period that already has any form definition is skipped, so
-- this never overwrites a form someone has started editing. Run with
--   psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -f supabase/seed/camp-hope-forms.sql

do $do$
declare
  v_camp_slug constant text := 'camphope';
  v_forms     constant jsonb := $elexio$${formsJson}$elexio$::jsonb;

  v_camp_id   uuid;
  v_season_id uuid;
  v_period_id uuid;
  v_form_id   uuid;
  v_form      jsonb;
begin
  select id into v_camp_id from public.camps where slug = v_camp_slug;
  if v_camp_id is null then
    raise exception 'No camp with slug %', v_camp_slug;
  end if;

  select id into v_season_id
    from public.seasons
   where camp_id = v_camp_id and is_active
   order by year desc
   limit 1;
  if v_season_id is null then
    raise exception 'Camp % has no active season', v_camp_slug;
  end if;

  for v_form in select value from jsonb_array_elements(v_forms) loop
    select id into v_period_id
      from public.registration_periods
     where season_id = v_season_id and audience = v_form->>'audience';

    if v_period_id is null then
      raise notice 'No % registration period in the active season; skipped.', v_form->>'audience';
      continue;
    end if;

    if exists (select 1 from public.form_definitions where period_id = v_period_id) then
      raise notice 'The % period already has a form; left untouched.', v_form->>'audience';
      continue;
    end if;

    insert into public.form_definitions
      (camp_id, period_id, version, title, intro_text, success_text, published_at)
    values
      (v_camp_id, v_period_id, 1, v_form->>'title', v_form->>'intro_text', v_form->>'success_text', null)
    returning id into v_form_id;

    insert into public.form_fields
      (camp_id, form_id, field_key, label, help_text, field_type, required,
       options, visible_when, section, repeat_count_field, display_order)
    select v_camp_id,
           v_form_id,
           f->>'field_key',
           f->>'label',
           f->>'help_text',
           f->>'field_type',
           (f->>'required')::boolean,
           coalesce(f->'options', '[]'::jsonb),
           case when jsonb_typeof(f->'visible_when') = 'object' then f->'visible_when' end,
           f->>'section',
           f->>'repeat_count_field',
           (t.ord - 1)::int
      from jsonb_array_elements(v_form->'fields') with ordinality as t(f, ord);

    raise notice 'Added % draft with % questions.', v_form->>'audience', jsonb_array_length(v_form->'fields');
  end loop;
end;
$do$;
`
);

// 3. Pricing --------------------------------------------------------------------------
const pricing = forms.find((f) => f.audience === "new_family")?.pricing;
const returning = forms.find((f) => f.audience === "returning_family")?.pricing;
if (!pricing || JSON.stringify(pricing) !== JSON.stringify(returning)) {
  throw new Error("The two family forms disagree on price; resolve that before generating tiers.");
}
if (pricing.early_amount_cents === null || !pricing.early_ends_on) {
  throw new Error("Expected an early price and date on the camper block.");
}
const [, earlyMonth, earlyDay] = pricing.early_ends_on.split("-").map(Number);
const tiers = perCamperTiers(pricing);
const values = (rows: typeof tiers) =>
  rows
    .map((t) => `(v_camp_id, v_season_id, ${t.camper_count}, ${t.early_cents}, ${t.regular_cents})`)
    .join(",\n    ");

writeFileSync(
  join(root, "supabase/seed/camp-hope-pricing.sql"),
  `-- ${HEADER}
--
-- Camp Hope tuition for the active season, from the Elexio camper block:
--   $${pricing.amount_cents / 100} per camper, $${pricing.early_amount_cents / 100} per camper before ${pricing.early_ends_on.slice(5)} (Elexio's ${pricing.early_ends_on.slice(0, 4)} date,
--   carried to the active season's year). Up to ${pricing.max_campers} campers per registration.
--
-- pricing_tiers holds the TOTAL for a household of N campers, and
-- family_tuition_cents() charges the largest tier <= the family's camper count.
--
-- Tier 1 is exact and is upserted. Tiers 2-${pricing.max_campers} are N x the per-camper price:
-- Elexio gave families a discount through codes (2 GENESIS, 3 TRINITY,
-- 4 GOSPEL, 5 OMEGA), but the discount AMOUNTS live in Elexio's admin and are
-- not in the form data. They are inserted only when missing, so once a
-- director enters the real discounted totals, re-running this leaves them be.
-- A ${pricing.max_campers}-camper tier is included because the forms allow ${pricing.max_campers} campers; without
-- it a ${pricing.max_campers}-camper family would be charged the 4-camper total.
--
-- Pay Later stays available: registration creates the invoice and schedule
-- without taking a card, and a check is recorded from Finance as an offline
-- payment.

do $do$
declare
  v_camp_slug constant text := 'camphope';
  v_camp_id   uuid;
  v_season_id uuid;
  v_year      int;
begin
  select id into v_camp_id from public.camps where slug = v_camp_slug;
  if v_camp_id is null then
    raise exception 'No camp with slug %', v_camp_slug;
  end if;

  select id, year into v_season_id, v_year
    from public.seasons
   where camp_id = v_camp_id and is_active
   order by year desc
   limit 1;
  if v_season_id is null then
    raise exception 'Camp % has no active season', v_camp_slug;
  end if;

  -- The early rate applies before this date (family_tuition_cents: as_of < date).
  update public.seasons
     set early_rate_ends_on = make_date(v_year, ${earlyMonth}, ${earlyDay})
   where id = v_season_id;

  insert into public.pricing_tiers (camp_id, season_id, camper_count, early_cents, regular_cents)
  values
    ${values(tiers.slice(0, 1))}
  on conflict (season_id, camper_count) do update
    set early_cents = excluded.early_cents,
        regular_cents = excluded.regular_cents;

  insert into public.pricing_tiers (camp_id, season_id, camper_count, early_cents, regular_cents)
  values
    ${values(tiers.slice(1))}
  on conflict (season_id, camper_count) do nothing;
end;
$do$;
`
);

for (const f of forms) {
  console.log(`${f.audience.padEnd(17)} ${String(f.fields.length).padStart(3)} rows  ${f.title}`);
}
